const showreelsDb = [
  {
    name: "Sound",
    video: "/images/showreels/sound.mp4",
    description:
      "Dragons don't exist they said. They are the stuff of legend and people's imagination. Greg would have agreed with this assessment without a second thought 24 hours ago. But now that there was a dragon staring directly into his eyes, he questioned everything that he had been told. Dragons don't exist they said. They are the stuff of legend and people's imagination. Greg would have agreed with this assessment without a second thought 24 hours ago. But now that there was a dragon staring directly into his eyes, he questioned everything that he had been told. Dragons don't exist they said. They are the stuff of legend and people's imagination. Greg would have agreed with this assessment without a second thought 24 hours ago. But now that there was a dragon staring directly into his eyes, he questioned everything that he had been told. Dragons don't exist they said. They are the stuff of legend and people's imagination. Greg would have agreed with this assessment without a second thought 24 hours ago. But now that there was a dragon staring directly into his eyes, he questioned everything that he had been told. Dragons don't exist they said. They are the stuff of legend and people's imagination. Greg would have agreed with this assessment without a second thought 24 hours ago. But now that there was a dragon staring directly into his eyes, he questioned everything that he had been told. Dragons don't exist they said. They are the stuff of legend and people's imagination. Greg would have agreed with this assessment without a second thought 24 hours ago. But now that there was a dragon staring directly into his eyes, he questioned everything that he had been told.",
  },
  {
    name: "Directing",
    video: "/images/showreels/directing.mp4",
    description:
      "What have you noticed today? I noticed that if you outline the eyes, nose, and mouth on your face with your finger, you make an 'I' which makes perfect sense, but is something I never noticed before. What have you noticed today? What have you noticed today? I noticed that if you outline the eyes, nose, and mouth on your face with your finger, you make an 'I' which makes perfect sense, but is something I never noticed before. What have you noticed today? What have you noticed today? I noticed that if you outline the eyes, nose, and mouth on your face with your finger, you make an 'I' which makes perfect sense, but is something I never noticed before. What have you noticed today? What have you noticed today? I noticed that if you outline the eyes, nose, and mouth on your face with your finger, you make an 'I' which makes perfect sense, but is something I never noticed before. What have you noticed today? What have you noticed today? I noticed that if you outline the eyes, nose, and mouth on your face with your finger, you make an 'I' which makes perfect sense, but is something I never noticed before. What have you noticed today? What have you noticed today? I noticed that if you outline the eyes, nose, and mouth on your face with your finger, you make an 'I' which makes perfect sense, but is something I never noticed before. What have you noticed today?",
  },
  {
    name: "All of it",
    video: "/images/showreels/allofit.mp4",
    description:
      "The headache wouldn't go away. She's taken medicine but even that didn't help. The monstrous throbbing in her head continued. She had this happen to her only once before in her life and she realized that only one thing could be happening. The headache wouldn't go away. She's taken medicine but even that didn't help. The monstrous throbbing in her head continued. She had this happen to her only once before in her life and she realized that only one thing could be happening. The headache wouldn't go away. She's taken medicine but even that didn't help. The monstrous throbbing in her head continued. She had this happen to her only once before in her life and she realized that only one thing could be happening. The headache wouldn't go away. She's taken medicine but even that didn't help. The monstrous throbbing in her head continued. She had this happen to her only once before in her life and she realized that only one thing could be happening. The headache wouldn't go away. She's taken medicine but even that didn't help. The monstrous throbbing in her head continued. She had this happen to her only once before in her life and she realized that only one thing could be happening. The headache wouldn't go away. She's taken medicine but even that didn't help. The monstrous throbbing in her head continued. She had this happen to her only once before in her life and she realized that only one thing could be happening.",
  },
];

export { showreelsDb };
